### ISSUE TITLE
兼容旧版本？

### ISSUE THREAD

**Issue by xiaopangju** [QWERTY770/MCBBS-Wiki-Mod#23]
如题……
电脑太辣鸡，玩不了，但是我又是第一批mcbbs wiki用户，所以我想请求作者兼容旧版本

**Comment by MarbleGateKeeper** [comment]
> 如题……
> 电脑太辣鸡，玩不了，但是我又是第一批mcbbs wiki用户，所以我想请求作者兼容旧版本

没什么可能，1.12和1.13的Modding之间差别实在是太大了

**Comment by xiaopangju** [comment]
好吧
